# Travis-CI Build
# see travis-ci.org for details

dist: trusty
sudo: required
language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update -qq
    - sudo apt-get install cmake -qq
    - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-5; fi
    - sudo ln -s $(which gcc-5) /usr/local/bin/gcc
    - sudo apt-get install -qq libsdl2-dev

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
    - make VERBOSE=1
