# Travis-CI Build
# see travis-ci.org for details

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-5; fi
  - sudo ln -s $(which gcc-5) /usr/local/bin/gcc

script: make release